name: Update documentaion
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - docs/public

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
    - run: yarn install
      working-directory: docs/public
    - run: yarn build
      working-directory: docs/public
    - run: |
        git config --global user.name $GITHUB_ACTOR
        git config --global user.email $GITHUB_ACTOR@users.noreply.github.com
        yarn deploy --skip-build
      working-directory: docs/public
      env:
        GIT_USER: $GITHUB_ACTOR
        GIT_PASS: ${{ secrets.GITHUB_TOKEN }}
