name: Tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v3

      # .NET Tests
      - name: Build .NET
        uses: ./.github/actions/dotnet
        with:
          version: ${{ steps.release-version.outputs.next-version }}${{ github.event.inputs.version && 'pre' || '' }}

      - name: Test .NET Solution
        working-directory: src
        shell: bash
        run: dotnet test -c Release /p:CollectCoverage=true -m:1
        env:
          AzureServiceBusConnectionString: ${{ secrets.AZURE_SERVICE_BUS_CONNECTION_STRING }}

      - name: Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@v1.0.2
        with:
          filename: src/coverage.cobertura.xml
          badge: true
          format: 'markdown'
          output: 'both'

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md
